/* DAOITH service marketplace catalog */
window.DAOITH_SERVICES = [
  {
    id: 'consult-1v1',
    category: 'consult',
    title: '专家1v1财税咨询',
    desc: '资深跨境财税专家一对一深度咨询，覆盖架构规划、合规诊断、退税优化',
    priceLabel: '¥2,999',
    priceValue: 2999,
    unit: '/小时',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '由资深跨境财税专家提供一对一深度咨询，围绕平台选择、店铺主体、发货模式、发票链条与出口退税路径进行诊断，并给出可落地的合规与节税建议。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '处于业务起步或架构调整阶段的跨境卖家、有复杂多国销售安排的企业财务负责人。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按小时计费；咨询后可提供要点纪要。建议提前准备平台、目的国、HS 编码与年销售额等信息。' },
    ],
  },
  {
    id: 'consult-annual',
    category: 'consult',
    title: '财税合规陪跑',
    desc: '全年财税合规陪跑服务，专家团队持续跟进，覆盖架构、账务、退税、海外税全链路',
    priceLabel: '¥98,000',
    priceValue: 98000,
    unit: '/年',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '全年陪伴式合规支持：季度复盘、政策更新解读、关键节点陪跑（退税申报、海外税注册、汇算清缴等），专家团队远程/线上持续跟进。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '年销售额达到一定规模、需要持续合规陪跑而非单次咨询的跨境电商企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按年签约；含约定次数的专家会诊与书面纪要。具体服务清单以签约方案为准。' },
    ],
  },
  {
    id: 'domestic-diagnosis',
    category: 'domestic',
    title: '跨境电商税务合规诊断',
    desc: '全面诊断企业跨境税务合规状况，出具整改建议报告，含出口退税合规评估',
    priceLabel: '¥15,000',
    priceValue: 15000,
    unit: '/次',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '对企业跨境业务模式、发票与单证、报关与退税、主体架构进行全面诊断，输出整改优先级与行动清单。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '拟做出口退税、准备融资/IPO、或收到税局关注的跨境电商企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '交付《跨境税务合规诊断报告》一份，并安排一次解读会议。' },
    ],
  },
  {
    id: 'domestic-bookkeeping',
    category: 'domestic',
    title: '代理记账报税',
    desc: '跨境电商企业代理记账、纳税申报、汇算清缴一站式服务',
    priceLabel: '¥800',
    priceValue: 800,
    unit: '/月起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '日常记账、增值税与附加税申报、企业所得税预缴与汇算清缴协助，适配跨境电商平台回款与多币种场景。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '境内公司主体开展跨境电商、需要规范账务与纳税申报的企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按月服务；价格因票量与业务复杂度浮动，最终以方案报价为准。' },
    ],
  },
  {
    id: 'domestic-rebate',
    category: 'domestic',
    title: '出口退税代办',
    desc: '9810海外仓/9610零售出口退税申报全程代办，含单证整理与税局沟通',
    priceLabel: '¥3,000',
    priceValue: 3000,
    unit: '/次起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '协助整理出口报关、发票、物流与销售单据，完成退（免）税申报，并就补正材料与税局沟通提供支持。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '采用 9810 / 9610 等模式、具备退税条件的出口企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按次或按批次报价；复杂案件可能另行评估。' },
    ],
  },
  {
    id: 'domestic-setup',
    category: 'domestic',
    title: '公司注册与资质办理',
    desc: '跨境电商公司注册、进出口权、海关备案、电子口岸等资质一站式办理',
    priceLabel: '¥5,000',
    priceValue: 5000,
    unit: '/起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '公司设立、进出口权、海关备案、电子口岸等跨境经营基础资质办理与流程辅导。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '新设或补办资质的跨境电商创业团队与企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '费用因地区与加急需求而异；官方规费另计。' },
    ],
  },
  {
    id: 'overseas-vat',
    category: 'overseas',
    title: '欧洲VAT注册申报',
    desc: '英国、德国、法国等欧洲国家VAT注册与月度/季度申报服务',
    priceLabel: '¥3,500',
    priceValue: 3500,
    unit: '/国起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '协助完成目标国家 VAT 注册、申报周期安排与日常申报材料准备，说明平台代扣与卖家义务边界。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '在欧洲站销售、需注册或持续申报 VAT 的卖家。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按国家起步报价；含注册与首期申报辅导，持续申报可另签年服务。' },
    ],
  },
  {
    id: 'overseas-us-sales-tax',
    category: 'overseas',
    title: '美国销售税合规',
    desc: '美国各州销售税注册、申报与合规咨询，覆盖经济关联度规则',
    priceLabel: '¥5,000',
    priceValue: 5000,
    unit: '/州起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '评估经济关联（nexus）、协助州税注册与申报安排，梳理平台代收代缴与卖家自报边界。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '美国站卖家、独立站卖家及需多州合规的企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按州起步；多州打包可优惠报价。' },
    ],
  },
  {
    id: 'overseas-odi',
    category: 'overseas',
    title: 'ODI境外投资备案',
    desc: '境外投资备案全流程代办，含发改委、商务、外汇管理局三方审批',
    priceLabel: '¥30,000',
    priceValue: 30000,
    unit: '/起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '协助准备 ODI 材料，推进发改、商务与外汇相关流程，对接境外持股与资金出境路径说明。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '拟设立或收购境外子公司、海外仓主体的境内企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按项目报价；审批结果取决于主管部门，服务侧重材料与流程推进。' },
    ],
  },
  {
    id: 'overseas-company',
    category: 'overseas',
    title: '海外公司注册',
    desc: '香港、新加坡、美国、BVI等热门司法管辖区公司注册与秘书服务',
    priceLabel: '¥8,000',
    priceValue: 8000,
    unit: '/起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '热门司法管辖区公司注册、秘书与基础合规年检辅导，说明开户与税务登记衔接要点。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '需要境外收付款主体、品牌控股或海外仓运营主体的企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '价格因管辖区与加急选项不同；政府规费与银行开户另计。' },
    ],
  },
  {
    id: 'consult-tp',
    category: 'consult',
    title: '转让定价文档编制',
    desc: '关联交易转让定价同期资料、本地文档与主文档编制',
    priceLabel: '¥50,000',
    priceValue: 50000,
    unit: '/起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '梳理关联交易，编制同期资料、本地文档与主文档，支持合理定价方法选择与风险提示。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '存在境内外关联采购、服务费、特许权使用费等安排的集团企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '按项目复杂度报价；可配合年度更新服务。' },
    ],
  },
  {
    id: 'domestic-hte',
    category: 'domestic',
    title: '高新技术企业认定',
    desc: '高新技术企业资质申请辅导，含研发费用归集与知识产权布局',
    priceLabel: '¥20,000',
    priceValue: 20000,
    unit: '/起',
    details: [
      { type: 'h2', text: '服务内容' },
      { type: 'p', text: '辅导高新技术企业认定材料准备，协助研发费用归集与知识产权布局建议，提高申报材料完整性。' },
      { type: 'h2', text: '适用对象' },
      { type: 'p', text: '有研发投入、拟申请或复审高企资质的科技型与跨境相关企业。' },
      { type: 'h2', text: '交付说明' },
      { type: 'p', text: '辅导服务费用；认定结果由主管部门审定。' },
    ],
  },
];

window.getServiceById = function getServiceById(id) {
  return (window.DAOITH_SERVICES || []).find((s) => s.id === id) || null;
};

window.formatServicePrice = function formatServicePrice(value) {
  const n = Number(value) || 0;
  return `¥${n.toLocaleString('zh-CN')}`;
};
