/* 各地区税制 — 摘编自国家税务总局《国别（地区）投资税收指南》（税路通） */
window.DAOITH_TAX_SOURCE = {
  name: '国家税务总局《国别（地区）投资税收指南》',
  url: 'https://www.chinatax.gov.cn/chinatax/n810219/n810744/index.html',
  note: '以下内容摘编自税路通专栏发布的国别投资税收指南，涵盖东道国主要税种及与中国双边税收安排要点。具体税率与规则以东道国最新法规及官方指南全文为准。',
};

window.DAOITH_TAX_SYSTEMS = [
  {
    id: 'us',
    rank: 1,
    name: '美国',
    nameEn: 'United States',
    flag: '🇺🇸',
    trade2025: '5,597',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '联邦与州/local 三级税制。跨境卖家需关注联邦企业所得税、州销售税（无全国统一 VAT）及预提所得税。',
    taxes: [
      { label: '联邦企业所得税', value: '21%（2018年税改后法定税率）' },
      { label: '州及地方税', value: '因州而异；州企业所得税 0—11%+ 不等' },
      { label: '销售税', value: '无联邦 VAT；各州/地方销售税与「经济关联度」规则适用' },
      { label: '预提所得税', value: '股息/利息/特许权使用费等通常 30%，税收协定可减免' },
    ],
    treaty: '中美税收协定对股息、利息、特许权使用费及常设机构利润等设有优惠税率及相互协商程序。',
    tips: ['平台代扣代缴不等于完成全部州税合规', 'FBA 等仓储可能构成物理关联度', '需区分 LLC、C-Corp 等主体所得税处理'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '美国实行联邦、州和地方三级税收体系。联邦政府主要税种包括企业所得税、个人所得税、雇佣税、Excise 税等；州政府征收销售税、州所得税等；部分地方政府还有附加税。对跨境电子商务而言，销售税合规（各州 economic nexus）与联邦/州所得税往往是关注重点。' },
      { type: 'h2', text: '主要税种' },
      { type: 'p', text: '联邦企业所得税法定税率为 21%。州企业所得税税率因州而异，部分州不征收州所得税。美国没有全国统一的增值税，但对零售商品和服务普遍征收销售税，税率和规则由各州及地方自行规定。' },
      { type: 'h2', text: '与中双边安排' },
      { type: 'p', text: '中美双边税收协定及议定书对跨境支付的预提税税率、常设机构认定、相互协商程序等作出安排。企业应结合协定与国内法判断实际税负，并留存转让定价及受益所有人相关文档。' },
    ],
  },
  {
    id: 'hk',
    rank: 2,
    name: '中国香港',
    nameEn: 'Hong Kong SAR',
    flag: '🇭🇰',
    trade2025: '3,673',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '地域来源原则征税，无 VAT/GST。利得税两级制，跨境资金流动相对便利。',
    taxes: [
      { label: '利得税（公司）', value: '8.25%（首200万港元应评税利润）/ 16.5%（其余）' },
      { label: '利得税（独资/合伙）', value: '7.5% / 15% 两级制' },
      { label: '货物及服务税', value: '无 VAT/GST' },
      { label: '预提税', value: '通常不对外汇出股息等征收预提税' },
    ],
    treaty: '内地与香港签有《避免双重征税安排》及多项议定书，涵盖股息、利息、特许权使用费及资本收益等。',
    tips: ['需证明利润来源地以适用地域来源原则', '转口贸易需保留充分商业实质与文档', '与内地关联交易需关注转让定价'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '香港实行地域来源原则，仅对来源于香港的利润征收利得税。无增值税、销售税或资本增值税（特定资产除外）。税制简单、税率较低，是内地企业出海常用的控股与结算平台之一。' },
      { type: 'h2', text: '主要税种' },
      { type: 'p', text: '法团首 200 万港元应评税利润适用 8.25%，其余应评税利润 16.5%。无全球征税，离岸利润如确属离岸性质且满足实质要求，可申请离岸豁免。' },
    ],
  },
  {
    id: 'kr',
    rank: 3,
    name: '韩国',
    nameEn: 'Republic of Korea',
    flag: '🇰🇷',
    trade2025: '3,312',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '法人税与增值税并重，跨境平台销售需关注本地消费与常设机构规则。',
    taxes: [
      { label: '法人税', value: '标准 24%（含地方附加，综合税负约 24.2%）' },
      { label: '增值税', value: '10%' },
      { label: '预提所得税', value: '非居民股息/利息/特许权使用费等通常 22% 或 20%，协定减免' },
    ],
    treaty: '中韩税收协定对各类跨境支付及常设机构利润提供优惠税率与 MAP 机制。',
    tips: ['跨境电商平台可能触发本地 VAT 登记', '在韩仓储或代理或构成 PE', '转让定价文档要求较严'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '韩国主要税种包括法人税、增值税、个人综合所得税、继承赠与税等。法人税对居民企业全球所得征税，非居民仅就韩国来源所得征税。' },
      { type: 'h2', text: '增值税' },
      { type: 'p', text: '标准税率 10%，适用于在韩供应货物及劳务。跨境电商及数字服务需关注外国供应商登记及代扣义务。' },
    ],
  },
  {
    id: 'jp',
    rank: 4,
    name: '日本',
    nameEn: 'Japan',
    flag: '🇯🇵',
    trade2025: '3,222',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '法人税、消费税（增值税）双支柱，地方税附加使实际税负高于名义税率。',
    taxes: [
      { label: '法人税（实际税负）', value: '约 23—30%（含地方法人税、事业税等）' },
      { label: '消费税', value: '10%（标准税率）' },
      { label: '预提所得税', value: '非居民 20% 或协定税率' },
    ],
    treaty: '中日税收协定涵盖常设机构、海运空运、股息利息特许权使用费等条款。',
    tips: ['进口消费税与通关流程需协同', 'Amazon JP 等平台有本地合规要求', '年末调整与源泉征收制度复杂'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '日本对居民企业采用全世界范围征税，主要税种为法人税、消费税、所得税及各类地方税。法人税名义税率约 23.2%，加上地方法人税、事业税等，中小企业实际税负常见区间约 25—30%。' },
    ],
  },
  {
    id: 'tw',
    rank: 5,
    name: '中国台湾',
    nameEn: 'Taiwan, China',
    flag: '🇹🇼',
    trade2025: '3,143',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '营利事业所得税与营业税（增值税型）并行，对大陆企业投资有专门规定。',
    taxes: [
      { label: '营利事业所得税', value: '20%（2023年起一般企业）' },
      { label: '营业税', value: '5%（加值型及非加值型）' },
      { label: '营利事业所得税（境外所得）', value: '参与海外营运之所得纳入课税范围' },
    ],
    treaty: '两岸税收协议涵盖重复征税避免及信息交换安排（适用对象与程序须依法认定）。',
    tips: ['跨境电商涉及进口营业税与报关', '与大陆关联交易定价受关注', '需区分在大陆注册企业赴台投资规则'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '台湾主要税种包括营利事业所得税、综合所得税、营业税、货物税等。营利事业所得税对登记在台湾境内之公司所得课征，税率 20% 为现行一般税率。' },
    ],
  },
  {
    id: 'vn',
    rank: 6,
    name: '越南',
    nameEn: 'Vietnam',
    flag: '🇻🇳',
    trade2025: '2,961',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '企业所得税与增值税为主，加工贸易与跨境电商增长带动合规需求上升。',
    taxes: [
      { label: '企业所得税（CIT）', value: '标准 20%；优惠行业可 10—17%' },
      { label: '增值税', value: '标准 10%；部分商品 5% 或 0%' },
      { label: '预提税', value: '非居民 5—10% 或协定税率' },
    ],
    treaty: '中越税收协定对股息、利息、特许权使用费及技术服务费等有优惠安排。',
    tips: ['外商直接投资行业目录限制', '转让定价及关联交易申报', '电子发票与税务数字化加速'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '越南对企业征收企业所得税，对货物与劳务征收增值税。出口导向型制造业及跨境电商配套仓储增多，企业需关注本地实体、发票及外汇管理要求。' },
    ],
  },
  {
    id: 'ru',
    rank: 7,
    name: '俄罗斯',
    nameEn: 'Russia',
    flag: '🇷🇺',
    trade2025: '2,281',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '联邦统一税制，利润税与增值税为核心，近年受国际制裁与汇率波动影响较大。',
    taxes: [
      { label: '利润税', value: '标准 20%（联邦 3% + 地方 17%）' },
      { label: '增值税', value: '标准 20%；部分商品 10% 或 0%' },
      { label: '预提所得税', value: '非居民 15—20% 或协定税率' },
    ],
    treaty: '中俄税收协定对跨境支付及常设机构有详细条款，能源与资源行业适用特殊规定较多。',
    tips: ['收付汇与合规银行渠道', '本地化数据及电子发票要求', '制裁环境下合同与税务风险并重'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '俄罗斯实行联邦与地区共享的税收体系。利润税和增值税是最主要税种。对非居民企业，来源于俄罗斯境内的收入通常需在当地纳税或按预提税处理。' },
    ],
  },
  {
    id: 'de',
    rank: 8,
    name: '德国',
    nameEn: 'Germany',
    flag: '🇩🇪',
    trade2025: '2,111',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '欧盟 VAT 体系核心成员国，企业所得税加贸易税使实际税负接近 30%。',
    taxes: [
      { label: '企业所得税', value: '联邦 15% + 团结附加 5.5% + 市政贸易税（约 7—17%）' },
      { label: '增值税', value: '标准 19%；降低税率 7%' },
      { label: '预提税', value: '股息/特许权使用费等通常 25% 或协定税率' },
    ],
    treaty: '中德税收协定及欧盟指令共同影响跨境支付与集团内部安排。',
    tips: ['OSS/IOSS 等欧盟跨境电商 VAT 规则', '德国仓储触发 VAT 注册', '包装法 EPR 合规'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '德国是欧盟最大经济体，增值税合规是跨境电商卖家进入欧洲的关键。企业所得税由联邦企业所得税、团结附加税和市政贸易税组成，实际综合税负因地区而异，通常在 30% 左右。' },
    ],
  },
  {
    id: 'au',
    rank: 9,
    name: '澳大利亚',
    nameEn: 'Australia',
    flag: '🇦🇺',
    trade2025: '2,066',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '公司所得税与 GST 为主，低价值进口商品 GST 规则影响跨境电商。',
    taxes: [
      { label: '公司所得税', value: '30%（基准税率实体 25%）' },
      { label: 'GST', value: '10%' },
      { label: '预提税', value: '非居民 30% 或协定税率（股息等）' },
    ],
    treaty: '中澳自贸协定与税收协定共同作用于货物与服务贸易。',
    tips: ['年营业额 7.5 万澳元 GST 注册门槛', '平台代扣 GST 规则', '转让定价文档本地化要求'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '澳大利亚对居民企业全球所得征收公司所得税，非居民企业就澳大利亚来源所得纳税。GST 适用于大多数商品与服务，跨境电商低价值商品规则需特别关注。' },
    ],
  },
  {
    id: 'my',
    rank: 10,
    name: '马来西亚',
    nameEn: 'Malaysia',
    flag: '🇲🇾',
    trade2025: '1,917',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '企业所得税与 SST（销售与服务税）并行，部分行业仍适用服务税规则。',
    taxes: [
      { label: '企业所得税', value: '标准 24%（中小企业可享阶梯优惠）' },
      { label: 'SST', value: '销售税 5—10%；服务税 6—8%（行业差异）' },
      { label: '预提税', value: '非居民 10% 或协定税率' },
    ],
    treaty: '中马税收协定涵盖股息、利息、特许权使用费及技术援助费。',
    tips: ['转口与制造并存需区分适用税则', 'LHDN 数字化申报', '中资设厂关注 Pioneer Status 等优惠'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '马来西亚于 2018 年用 SST 取代 GST（部分时期）。企业所得税标准税率 24%，对符合资格的中小企业及 PROMOTION 活动有减免安排。' },
    ],
  },
  {
    id: 'br',
    rank: 11,
    name: '巴西',
    nameEn: 'Brazil',
    flag: '🇧🇷',
    trade2025: '1,880',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '税制复杂，联邦/州/市多级流转税并存，电商合规成本较高。',
    taxes: [
      { label: 'IRPJ/CSLL（企业所得税）', value: '合计约 34%（含附加，因制度而异）' },
      { label: 'ICMS（州流转税）', value: '州际 7—18% 不等，规则复杂' },
      { label: 'PIS/COFINS', value: '联邦社会贡献，累积/非累积制差异大' },
    ],
    treaty: '中巴税收协定对股息、利息、特许权使用费等有约定，实务操作需本地专业支持。',
    tips: ['Simples Nacional 小企业税制', '跨境电商进口 PRC 计划', '州际 ICMS 差异显著'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '巴西被普遍认为税制全球最复杂之一，联邦、州、市三级税种叠加。跨境电商涉及进口清关、州 ICMS 及联邦社会贡献，需整体规划而非单一税种优化。' },
    ],
  },
  {
    id: 'id',
    rank: 12,
    name: '印度尼西亚',
    nameEn: 'Indonesia',
    flag: '🇮🇩',
    trade2025: '1,675',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '企业所得税与增值税（PPN）为主，数字服务与电商监管趋严。',
    taxes: [
      { label: '企业所得税', value: '标准 22%（2022年起）' },
      { label: '增值税（PPN）', value: '11%（逐步提高至 12% 路径）' },
      { label: '预提税', value: '非居民 20% 或协定税率' },
    ],
    treaty: '中印尼税收协定对各类跨境支付设有优惠税率。',
    tips: ['PMSE 数字增值税规则', '外资持股负面清单', '本地化发票与 e-Faktur'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '印尼对居民企业全球所得征收企业所得税，增值税适用于国内交付之货物与劳务。跨境电商及数字平台需关注 PMSE 机制下的 VAT 代扣代缴。' },
    ],
  },
  {
    id: 'in',
    rank: 13,
    name: '印度',
    nameEn: 'India',
    flag: '🇮🇳',
    trade2025: '1,556',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: 'GST 统一间接税体系，企业所得税因企业类型与优惠不同差异较大。',
    taxes: [
      { label: '企业所得税', value: '一般 25—30%；新制造等可享 15—22% 优惠' },
      { label: 'GST', value: '5% / 12% / 18% / 28% 多档' },
      { label: 'TDS 预提', value: '对非居民支付广泛适用' },
    ],
    treaty: '中印税收协定对常设机构、技术服务费及股息等有规定。',
    tips: ['GSTIN 注册与申报', 'Equalisation Levy 数字税', '进口 IGST 与海关协同'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '印度 2017 年引入 GST 改革，整合原有多种间接税。企业所得税仍区分国内公司、外国公司及新设制造企业的优惠税率，跨境电商需同时处理 GST 与海关进口环节税。' },
    ],
  },
  {
    id: 'th',
    rank: 14,
    name: '泰国',
    nameEn: 'Thailand',
    flag: '🇹🇭',
    trade2025: '1,533',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '企业所得税与 VAT 为主，BOI 优惠吸引制造业与区域总部。',
    taxes: [
      { label: '企业所得税', value: '标准 20%' },
      { label: '增值税', value: '7%（法定 10%，目前减按 7% 执行）' },
      { label: '预提税', value: '非居民 15% 或协定税率' },
    ],
    treaty: '中泰税收协定对股息、利息、特许权使用费等有优惠税率。',
    tips: ['BOI 促进优惠申请', '跨境电商 VAT 登记门槛', '外汇管制与利润汇出'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '泰国对居民企业全球所得征收企业所得税，标准税率 20%。增值税标准法定 10%，现阶段政府多次延长 7% 优惠税率执行期，需关注政策更新。' },
    ],
  },
  {
    id: 'sg',
    rank: 15,
    name: '新加坡',
    nameEn: 'Singapore',
    flag: '🇸🇬',
    trade2025: '1,193',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '低税率枢纽，属地征税，无资本利得税，GST 近期上调。',
    taxes: [
      { label: '企业所得税', value: '17%（多种初创及研发优惠）' },
      { label: 'GST', value: '9%（2024年起）' },
      { label: '预提税', value: '股息等通常免预提；部分支付 10—17%' },
    ],
    treaty: '中新税收协定被广泛用作区域控股架构工具，需满足经济实质要求。',
    tips: ['实质与经济实质测试', 'GST 注册门槛 S$100 万', '区域 HQ 与 IP 规划'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '新加坡采用属地征税原则，企业所得税率 17%，无资本利得税。作为区域金融与物流枢纽，与中国贸易联系紧密，是跨境电商东南亚布局常见节点。' },
    ],
  },
  {
    id: 'nl',
    rank: 16,
    name: '荷兰',
    nameEn: 'Netherlands',
    flag: '🇳🇱',
    trade2025: '1,143',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '欧盟物流门户，企业所得税与 VAT 规则与欧盟体系一致。',
    taxes: [
      { label: '企业所得税', value: '标准 25.8%（2023年起）' },
      { label: '增值税', value: '标准 21%；降低 9%' },
      { label: '预提税', value: '股息/利息等 15% 或协定/指令减免' },
    ],
    treaty: '中荷税收协定及 EU 母子公司指令影响集团分红安排。',
    tips: ['阿姆斯特丹/鹿特丹仓配触发 VAT', '欧盟 IOSS/OSS 合规', '参与豁免与利息扣除限制'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '荷兰是欧盟重要进口分拨中心，跨境电商常用荷兰仓覆盖欧盟市场。增值税与海关程序与欧盟统一规则衔接，企业所得税率 25.8%。' },
    ],
  },
  {
    id: 'mx',
    rank: 17,
    name: '墨西哥',
    nameEn: 'Mexico',
    flag: '🇲🇽',
    trade2025: '1,094',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '联邦企业所得税与 VAT 为主，USMCA 框架下供应链联系紧密。',
    taxes: [
      { label: '企业所得税', value: '30%' },
      { label: '增值税（IVA）', value: '标准 16%；边境地区 8%' },
      { label: '预提税', value: '非居民 10—35% 或协定税率' },
    ],
    treaty: '中墨税收协定对跨境支付及常设机构有安排。',
    tips: ['SAT 电子发票 CFDI', '跨境电商进口简化程序', 'Maquiladora 保税制造规则'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '墨西哥企业所得税法定 30%，增值税标准 16%。作为北美供应链延伸节点，与中国在制造业与跨境电商领域贸易活跃。' },
    ],
  },
  {
    id: 'sa',
    rank: 18,
    name: '沙特阿拉伯',
    nameEn: 'Saudi Arabia',
    flag: '🇸🇦',
    trade2025: '1,082',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '伊斯兰金融背景下的现代 VAT 体系，2030 愿景带动外资准入。',
    taxes: [
      { label: '企业所得税', value: '非石油行业 20%；石油天然气 50—85%' },
      { label: '增值税', value: '15%' },
      { label: '预提税（Zakat 相关）', value: '沙特籍股东适用 Zakat；非居民 5—20%' },
    ],
    treaty: '中沙税收安排及投资保护协定支持双边经贸。',
    tips: ['沙特化用工要求', 'VAT 登记与 e-invoicing', '自贸区与 RHQ 计划优惠'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '沙特 2018 年引入 5% VAT 后 2020 年上调至 15%。非石油领域企业所得税 20%，与海湾国家传统低税模式相比已显著现代化。' },
    ],
  },
  {
    id: 'ae',
    rank: 19,
    name: '阿联酋',
    nameEn: 'United Arab Emirates',
    flag: '🇦🇪',
    trade2025: '1,080',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '2023 年起引入联邦企业所得税，自由区与 mainland 规则差异大。',
    taxes: [
      { label: '企业所得税', value: '9%（应税所得超过 37.5 万迪拉姆部分；2023年6月起）' },
      { label: '增值税', value: '5%' },
      { label: '自由区', value: '符合条件之 QFZP 仍可能 0% 企业税' },
    ],
    treaty: '中阿（联酋）税收协定支持跨境投资与常设机构安排。',
    tips: ['区分 mainland 与 free zone', '经济实质与受益所有人', 'Transfer pricing 文档'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '阿联酋长期以无联邦企业所得税著称，2023 年起实施 9% 联邦企业税。增值税 5% 自 2018 年实施。跨境电商经迪拜/阿布扎比转运至中东非市场较为常见。' },
    ],
  },
  {
    id: 'gb',
    rank: 20,
    name: '英国',
    nameEn: 'United Kingdom',
    flag: '🇬🇧',
    trade2025: '1,037',
    tradeUnit: '亿美元',
    tradeSource: '海关总署 2025年1—12月',
    summary: '脱欧后独立 VAT 体系，企业所得税与海关规则与欧盟脱钩。',
    taxes: [
      { label: '企业所得税', value: '25%（2023年4月起主税率；小企业阶梯税率）' },
      { label: '增值税', value: '标准 20%；降低 5% / 零税率' },
      { label: '预提税', value: '股息 0%（英国不预提）；其他支付视情况' },
    ],
    treaty: '中英税收协定对跨境支付、常设机构及海运空运有详细规定。',
    tips: ['HMRC 跨境电商 VAT', 'Northern Ireland 特殊安排', 'MTD 数字化申报'],
    sections: [
      { type: 'h2', text: '税制概况' },
      { type: 'p', text: '英国脱离欧盟后保留独立 VAT 及海关制度。企业所得税主税率 25%，中小企业适用较低阶梯税率。跨境电商卖家需关注 UK VAT 注册及 Postponed VAT Accounting 等工具。' },
    ],
  },
];

window.getTaxSystemById = function getTaxSystemById(id) {
  return window.DAOITH_TAX_SYSTEMS.find((c) => c.id === id);
};
